# Generated by Django 2.0.3 on 2019-12-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gpa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=64)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='skillsets',
            field=models.ManyToManyField(to='studygroups.SkillSet'),
        ),
    ]
