# Generated by Django 2.0.3 on 2019-12-02 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='skillsets',
        ),
        migrations.AddField(
            model_name='skillset',
            name='criteria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studygroups.Criteria'),
            preserve_default=False,
        ),
    ]
