# Generated by Django 2.0.3 on 2020-03-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0004_auto_20200325_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
